# Generated by Django 5.0.6 on 2024-07-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='beers.beer')),
            ],
        ),
    ]
